services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: nootrouser
      POSTGRES_PASSWORD: nootropass
      POSTGRES_DB: nootrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nootrouser -d nootrodb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 